include/oneapi/dpl/pstl/utils_ranges.h - fix compile error: replace get_count() method call to __get_buffer_size() call
	In file included from /oneDPL/oneDPL/test/parallel_api/ranges/adjacent_find_ranges_sycl.pass.cpp:18:
	In file included from /oneDPL/oneDPL/include/oneapi/dpl/execution:70:
	In file included from /oneDPL/oneDPL/include/oneapi/dpl/pstl/algorithm_impl.h:28:
	In file included from /oneDPL/oneDPL/include/oneapi/dpl/pstl/execution_impl.h:22:
	In file included from /oneDPL/oneDPL/include/oneapi/dpl/pstl/parallel_backend.h:32:
	In file included from /oneDPL/oneDPL/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h:34:
	/oneDPL/oneDPL/include/oneapi/dpl/pstl/hetero/dpcpp/../../utils_ranges.h:187:51: error: 'get_count' is deprecated: get_count() is deprecated, please use size() instead [-Werror,-Wdeprecated-declarations]
	  187 | __check_size(int) -> decltype(std::declval<_R&>().get_count());
		  |                                                   ^
	/oneDPL/oneDPL/include/oneapi/dpl/pstl/hetero/dpcpp/../../utils_ranges.h:208:52: note: while substituting explicitly-specified template arguments into function template '__check_size'
	  208 | using __difference_t = std::make_signed_t<decltype(__check_size<_R>(0))>;
		  |                                                    ^
	/oneDPL/oneDPL/include/oneapi/dpl/pstl/glue_algorithm_ranges_impl.h:1473:98: note: in instantiation of template type alias '__difference_t' requested here
	 1473 | oneapi::dpl::__internal::__enable_if_execution_policy<_ExecutionPolicy, oneapi::dpl::__internal::__difference_t<_Range>>
		  |                                                                                                  ^
	/oneDPL/oneDPL/test/parallel_api/ranges/adjacent_find_ranges_sycl.pass.cpp:46:16: note: while substituting deduced template arguments into function template 'adjacent_find' [with _ExecutionPolicy = const oneapi::dpl::execution::device_policy<> &, _Range = sycl::buffer<int> &, _BinaryPredicate = TestUtils::IsEqual<int>]
	   46 |         res2 = adjacent_find(CLONE_TEST_POLICY_IDX(exec, 1), A, TestUtils::IsEqual<int>());
		  |                ^
	/oneDPL/oneDPL/test/parallel_api/ranges/adjacent_find_ranges_sycl.pass.cpp:61:5: note: in instantiation of function template specialization 'test_impl<oneapi::dpl::execution::device_policy<> &>' requested here
	   61 |     test_impl(policy);
		  |     ^
	/opt/intel/oneapi/compiler/2025.2/bin/compiler/../../include/sycl/buffer.hpp:497:3: note: 'get_count' has been explicitly marked deprecated here
	  497 |   __SYCL2020_DEPRECATED("get_count() is deprecated, please use size() instead")
		  |   ^
	/opt/intel/oneapi/compiler/2025.2/bin/compiler/../../include/sycl/detail/defines_elementary.hpp:62:40: note: expanded from macro '__SYCL2020_DEPRECATED'
	   62 | #define __SYCL2020_DEPRECATED(message) __SYCL_DEPRECATED(message)
		  |                                        ^
	/opt/intel/oneapi/compiler/2025.2/bin/compiler/../../include/sycl/detail/defines_elementary.hpp:53:38: note: expanded from macro '__SYCL_DEPRECATED'
	   53 | #define __SYCL_DEPRECATED(message) [[deprecated(message)]]
		  |                                      ^