include/oneapi/dpl/internal/version_impl.h - fix compile error under Clang 14.0.0
 - compile error:

		/usr/bin/clang++ -DTEST_LONG_RUN=1 -O0 -g CMakeFiles/header_inclusion_order_numeric_0.pass.dir/general/header_inclusion_order_numeric_0.pass.cpp.o -o header_inclusion_order_numeric_0.pass  /localdisk/tools/inteloneapi_tbb/tbb/latest/lib/intel64/gcc4.8/libtbb_debug.so.12
		In file included from /test/general/header_inclusion_order_memory_0.pass.cpp:18:
		In file included from /include/oneapi/dpl/execution:23:
		In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/execution:32:
		In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/pstl/glue_execution_defs.h:50:
		In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/pstl/algorithm_impl.h:13:
		In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/iterator:61:
		In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_iterator_base_types.h:71:
		/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:979:13: error: no matching function for call to '__begin'
				= decltype(ranges::__cust_access::__begin(std::declval<_Tp&>()));
						   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/ranges_base.h:590:5: note: in instantiation of template type alias '__range_iter_t' requested here
			using iterator_t = std::__detail::__range_iter_t<_Tp>;
			^
		/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/ranges_util.h:98:43: note: in instantiation of template type alias 'iterator_t' requested here
			  data() requires contiguous_iterator<iterator_t<_Derived>>
												  ^
		/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/ranges_util.h:203:29: note: in instantiation of template class 'std::ranges::view_interface<std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized>>' requested here
			class subrange : public view_interface<subrange<_It, _Sent, _Kind>>
									^
		/test/general/header_inclusion_order_memory_0.pass.cpp:35:27: note: in instantiation of template class 'std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized>' requested here
			std::ranges::subrange subrange(ptr.get(), ptr.get() + n);
								  ^
		/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:963:7: note: candidate template ignored: constraints not satisfied [with _Tp = std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized>]
			  __begin(_Tp& __t)
			  ^
		/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:961:16: note: because 'is_array_v<std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized> >' evaluated to false
			  requires is_array_v<_Tp> || __member_begin<_Tp&> || __adl_begin<_Tp&>
					   ^
		/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:961:35: note: and 'std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized> &' does not satisfy '__member_begin'
			  requires is_array_v<_Tp> || __member_begin<_Tp&> || __adl_begin<_Tp&>
										  ^
		/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:944:23: note: because '__decay_copy(__t.begin())' would be invalid: no member named 'begin' in 'std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized>'
				  { __decay_copy(__t.begin()) } -> input_or_output_iterator;
									 ^
		/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:961:59: note: and 'std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized> &' does not satisfy '__adl_begin'
			  requires is_array_v<_Tp> || __member_begin<_Tp&> || __adl_begin<_Tp&>
																  ^
		/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:955:19: note: because '__decay_copy(begin(__t))' would be invalid: call to deleted function 'begin'
				  { __decay_copy(begin(__t)) } -> input_or_output_iterator;
								 ^
		/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:979:13: error: no matching function for call to '__begin'
				= decltype(ranges::__cust_access::__begin(std::declval<_Tp&>()));
						   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/ranges_base.h:590:5: note: in instantiation of template type alias '__range_iter_t' requested here
			using iterator_t = std::__detail::__range_iter_t<_Tp>;
			^
		/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/ranges_util.h:104:25: note: in instantiation of template type alias 'iterator_t' requested here
				&& contiguous_iterator<iterator_t<const _Derived>>
									   ^
		/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/ranges_util.h:203:29: note: in instantiation of template class 'std::ranges::view_interface<std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized>>' requested here
			class subrange : public view_interface<subrange<_It, _Sent, _Kind>>
									^
		/test/general/header_inclusion_order_memory_0.pass.cpp:35:27: note: in instantiation of template class 'std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized>' requested here
			std::ranges::subrange subrange(ptr.get(), ptr.get() + n);
								  ^
		/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:963:7: note: candidate template ignored: constraints not satisfied [with _Tp = const std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized>]
			  __begin(_Tp& __t)
			  ^
		/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:961:16: note: because 'is_array_v<const std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized> >' evaluated to false
			  requires is_array_v<_Tp> || __member_begin<_Tp&> || __adl_begin<_Tp&>
					   ^
		/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:961:35: note: and 'const std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized> &' does not satisfy '__member_begin'
			  requires is_array_v<_Tp> || __member_begin<_Tp&> || __adl_begin<_Tp&>
										  ^
		/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:944:23: note: because '__decay_copy(__t.begin())' would be invalid: no member named 'begin' in 'std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized>'
				  { __decay_copy(__t.begin()) } -> input_or_output_iterator;
									 ^
		/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:961:59: note: and 'const std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized> &' does not satisfy '__adl_begin'
			  requires is_array_v<_Tp> || __member_begin<_Tp&> || __adl_begin<_Tp&>
																  ^
		/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:955:19: note: because '__decay_copy(begin(__t))' would be invalid: call to deleted function 'begin'
				  { __decay_copy(begin(__t)) } -> input_or_output_iterator;
								 ^