[oneDPL][tests] Add implementation of `std::ranges::partition` (#2771)
* Initial implementation of ranges::partition_copy for CPU

* Add a test for ranges::partition_copy

* Formatting

* Rename to avoid call ambiguity

* Fix a bug in the logic

* Improve diagnostics

* Fix a bug in indexing the mask

* Remove serial fallback

* Improve formatting

* Remove LLVM notice from a new file

* Change __parallel_partition_copy to take 3 ranges, use __parallel_transform_reduce_then_scan directly

* Make possible out-of-bounds pre-check the responsibility of write operations

* Fix errors, add _Bounded to __parallel_partition_copy

* Fix errors, add sizes to the partition_copy writer class

* Fix use-after-forwarding error

* Update partition_copy to not use __future (#2759)

* Associate __transform_result with write operations instead of passing through the call stack

* Support OOB checks and position recording in __write_partitioned

* Change back to use __parallel_reduce_then_scan_copy, unify return value with __parallel_copy_if

* Enable SYCL backend for ranges::partition_copy

* Formatting and fixes

* Add assertions for the values obtained from __parallel_reduce_then_scan_copy

* Correct the 1st output stop position in the OOB case

* Change __parallel_partition_copy to use __parallel_transform_reduce_then_scan directly (again)

* Remove __initial_oob_pos(), make __detect_oob_in_two_steps_v specialized for write operations

* Remove __detect_oob_in_two_steps_v, make __write_partitioned store two stop positions

* Correct stop positions in __parallel_partition_copy

* Fix calculation of the 1st output stop postion

* Fix the conditions for writing

* Change size_t to ptrdiff_t

* Restructure __write_partitioned code for the bounded case

* Address review feedback

* change zip_view to a tuple of ranges

* Address review feedback

* Formatting

* include/oneapi/dpl/pstl/glue_algorithm_ranges_impl.h - introduce struct __internal::__partition_fn

* glue_algorithm_ranges_defs.h - add forward declaration of struct __partition_fn;

* algorithm_ranges_impl.h, algorithm_ranges_impl_hetero.h - add implementations of __pattern_partition()

* std_ranges_partition.pass.cpp - add new test for std::ranges::partition

* std_ranges_partition.pass.cpp - add new test for std::ranges::partition (separate implementation due algorithm is unstable and we can't check data directly)

* include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h - fix an error in __pattern_partition + __hetero_tag

* algorithm_ranges_impl.h, algorithm_ranges_impl_hetero.h - add implementations of __pattern_partition()

* std_ranges_partition.pass.cpp - add new test for std::ranges::partition (separate implementation due algorithm is unstable and we can't check data directly)

* std_ranges_partition.pass.cpp - check non-borrowed ranges

* std_ranges_partition.pass.cpp - check non-borrowed ranges

* algorithm_ranges_impl.h - fix self-review comment

* std_ranges_partition.pass.cpp - test improvement

* std_ranges_partition.pass.cpp - test improvement

* std_ranges_partition.pass.cpp - fix compile errors: variable 'xxx' is not needed and will not be emitted

    test/parallel_api/ranges/std_ranges_partition.pass.cpp:29:6: error: variable 'gen_alternate' is not needed and will not be emitted [-Werror,-Wunneeded-internal-declaration]
    test/parallel_api/ranges/std_ranges_partition.pass.cpp:30:6: error: variable 'gen_blocked' is not needed and will not be emitted [-Werror,-Wunneeded-internal-declaration]

* std_ranges_partition.pass.cpp - simplify test

* std_ranges_partition.pass.cpp - formatting

* std_ranges_partition.pass.cpp - remove extra includes

* Update test/parallel_api/ranges/std_ranges_partition.pass.cpp

Co-authored-by: Dmitriy Sobolev <Dmitriy.Sobolev@intel.com>

* algorithm_ranges_impl.h - fix self review comment: we are able to use previously evaluated __last iterator due this iterator still valid

* algorithm_ranges_impl_hetero.h - fix self review comment: we are able to use previously evaluated __last iterator due this iterator still valid

* algorithm_ranges_impl.h - renames in __pattern_partition() for alignment with hetero implementation

---------

Co-authored-by: Alexey Kukanov <alexey.kukanov@intel.com>
Co-authored-by: Dmitriy Sobolev <Dmitriy.Sobolev@intel.com>